"use client"

import type React from "react"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Eye, Upload, FileImage, CheckCircle, AlertCircle, ArrowLeft, Download, X } from "lucide-react"
import Link from "next/link"

export default function ScreeningPage() {
  const [uploadedImage, setUploadedImage] = useState<string | null>(null)
  const [imageFile, setImageFile] = useState<File | null>(null)
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [analysisComplete, setAnalysisComplete] = useState(false)
  const [results, setResults] = useState<any>(null)
  const [showHeatmapModal, setShowHeatmapModal] = useState(false)
  const [heatmap, setHeatmap] = useState<string | null>(null)

  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (file) {
      const maxSize = 10 * 1024 * 1024 // 10MB in bytes
      if (file.size > maxSize) {
        alert("File size must be less than 10MB. Please choose a smaller image.")
        return
      }

      const allowedTypes = ["image/jpeg", "image/jpg", "image/png", "image/tiff"]
      if (!allowedTypes.includes(file.type)) {
        alert("Please upload a valid image file (JPG, PNG, or TIFF).")
        return
      }

      setImageFile(file)

      const reader = new FileReader()
      reader.onload = (e) => {
        setUploadedImage(e.target?.result as string)
        setAnalysisComplete(false)
        setResults(null)
      }
      reader.onerror = () => {
        alert("Error reading file. Please try again.")
      }
      reader.readAsDataURL(file)
    }
  }

  const triggerFileInput = () => {
    const fileInput = document.getElementById("image-upload") as HTMLInputElement
    if (fileInput) {
      fileInput.click()
    }
  }

  const triggerFileReupload = () => {
    const fileInput = document.getElementById("image-reupload") as HTMLInputElement
    if (fileInput) {
      fileInput.click()
    }
  }

  const startAnalysis = async () => {
  if (!imageFile) return;

  setIsAnalyzing(true);

  try {
    const formData = new FormData();
    formData.append("file", imageFile);

    // Call Next.js API route → which calls FastAPI backend
    const response = await fetch("/api/predict", {
      method: "POST",
      body: formData,
    });

    const data = await response.json();

    // Set heatmap later when you add GradCAM
    setHeatmap(null);

    setResults({
      riskLevel: data.prediction,
      confidence: (data.confidence * 100).toFixed(2),
      findings: [
        `AI Model Prediction: ${data.prediction}`,
        `Confidence Level: ${(data.confidence * 100).toFixed(2)}%`,
        "Analysis completed using real ML model",
      ],
      recommendation:
        data.prediction === "No_DR"
          ? "No signs of diabetic retinopathy detected."
          : "Clinical consultation recommended based on AI findings.",
    });

    setAnalysisComplete(true);
  } catch (error) {
    console.error("Analysis failed:", error);
    alert("Error analyzing image. Check backend console.");
  } finally {
    setIsAnalyzing(false);
  }
};


  const downloadReport = () => {
    if (!results || !uploadedImage) return

    // Create report content
    const reportContent = `
DIABETIC RETINOPATHY SCREENING REPORT
=====================================

Patient Information:
- Screening Date: ${new Date().toLocaleDateString()}
- Screening Time: ${new Date().toLocaleTimeString()}

Analysis Results:
- Risk Level: ${results.riskLevel}
- Confidence: ${results.confidence}%

Key Findings:
${results.findings.map((finding: string, index: number) => `${index + 1}. ${finding}`).join("\n")}

Recommendation:
${results.recommendation}

Technical Information:
- AI Model: RetinaScan AI v1.0
- Image Format: ${imageFile?.type || "Unknown"}
- Image Size: ${imageFile ? (imageFile.size / 1024 / 1024).toFixed(2) + " MB" : "Unknown"}

IMPORTANT MEDICAL DISCLAIMER:
This AI screening tool is designed to assist healthcare professionals and should not be used as a substitute for professional medical diagnosis, treatment, or advice. Always consult with qualified healthcare professionals for medical decisions. The results provided are for screening purposes only and require clinical correlation and professional interpretation.

Report generated by RetinaScan AI
© ${new Date().getFullYear()} RetinaScan AI. All rights reserved.
    `

    // Create and download the report
    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `RetinaScan_Report_${new Date().toISOString().split("T")[0]}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    window.URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-2">
              <Eye className="h-8 w-8 text-primary" />
              <span className="text-xl font-bold text-foreground">RetinaScan AI</span>
            </div>
            <div className="flex items-center space-x-4">
              <Link href="/">
                <Button variant="ghost" size="sm" className="flex items-center gap-2">
                  <ArrowLeft className="h-4 w-4" />
                  Back to Home
                </Button>
              </Link>
              <Link href="/signin">
                <Button variant="outline" size="sm">
                  Sign In
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="text-center mb-8">
            <Badge variant="secondary" className="mb-4">
              AI-Powered Screening
            </Badge>
            <h1 className="text-3xl md:text-4xl font-bold text-balance mb-4">Diabetic Retinopathy Screening</h1>
            <p className="text-lg text-muted-foreground text-pretty">
              Upload a retinal fundus image for AI-powered analysis and screening
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            {/* Upload Section */}
            <Card className="border-border">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Upload className="h-5 w-5" />
                  Upload Retinal Image
                </CardTitle>
                <CardDescription>Please upload a high-quality fundus photograph for analysis</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {!uploadedImage ? (
                  <div className="border-2 border-dashed border-border rounded-lg p-8 text-center">
                    <FileImage className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                    <p className="text-muted-foreground mb-4">
                      Drag and drop your retinal image here, or click to browse
                    </p>
                    <input
                      type="file"
                      accept="image/*"
                      capture="environment"
                      onChange={handleImageUpload}
                      className="hidden"
                      id="image-upload"
                    />
                    <Button variant="outline" onClick={triggerFileInput} className="cursor-pointer bg-transparent">
                      Choose File
                    </Button>
                    <p className="text-xs text-muted-foreground mt-2">
                      Supported formats: JPG, PNG, TIFF (Max 10MB) | Use camera or select from device
                    </p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    <div className="relative">
                      <img
                        src={uploadedImage || "/placeholder.svg"}
                        alt="Uploaded retinal image"
                        className="w-full h-64 object-cover rounded-lg border"
                      />
                      <Badge className="absolute top-2 right-2 bg-green-100 text-green-800">Image Uploaded</Badge>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        onClick={startAnalysis}
                        disabled={isAnalyzing || analysisComplete}
                        className="flex-1 bg-blue-600 hover:bg-blue-700"
                      >
                        {isAnalyzing ? "Analyzing..." : "Start Analysis"}
                      </Button>
                      <input
                        type="file"
                        accept="image/*"
                        capture="environment"
                        onChange={handleImageUpload}
                        className="hidden"
                        id="image-reupload"
                      />
                      <Button variant="outline" onClick={triggerFileReupload} className="cursor-pointer bg-transparent">
                        Change Image
                      </Button>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Results Section */}
            <Card className="border-border">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Eye className="h-5 w-5" />
                  Analysis Results
                </CardTitle>
                <CardDescription>AI-powered screening results and recommendations</CardDescription>
              </CardHeader>
              <CardContent>
                {!uploadedImage && (
                  <div className="text-center py-8">
                    <FileImage className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                    <p className="text-muted-foreground">Upload an image to begin analysis</p>
                  </div>
                )}

                {uploadedImage && !isAnalyzing && !analysisComplete && (
                  <div className="text-center py-8">
                    <AlertCircle className="h-12 w-12 text-yellow-500 mx-auto mb-4" />
                    <p className="text-muted-foreground">Ready for analysis. Click "Start Analysis" to begin.</p>
                  </div>
                )}

                {isAnalyzing && (
                  <div className="text-center py-8">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
                    <p className="text-muted-foreground">Analyzing retinal image with AI...</p>
                    <p className="text-sm text-muted-foreground mt-2">This usually takes 15-30 seconds</p>
                  </div>
                )}

                {analysisComplete && results && (
                  <div className="space-y-4">
                    <div className="flex items-center gap-2 mb-4">
                      <CheckCircle className="h-5 w-5 text-green-600" />
                      <span className="font-semibold text-green-600">Analysis Complete</span>
                    </div>

                    <div className="space-y-3">
                      <div className="flex justify-between items-center p-3 bg-muted rounded-lg">
                        <span className="font-medium">Risk Level:</span>
                        <Badge variant="secondary" className="bg-green-100 text-green-800">
                          {results.riskLevel}
                        </Badge>
                      </div>

                      <div className="flex justify-between items-center p-3 bg-muted rounded-lg">
                        <span className="font-medium">Confidence:</span>
                        <span className="font-semibold">{results.confidence}%</span>
                      </div>

                      <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg">
                        <div className="flex justify-between items-center mb-2">
                          <span className="font-medium text-slate-900">AI Decision Analysis:</span>
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => setShowHeatmapModal(true)}
                            className="bg-white hover:bg-slate-50 border-slate-300"
                          >
                            <Eye className="h-4 w-4 mr-2" />
                            View Heatmap
                          </Button>
                        </div>
                        <p className="text-sm text-slate-600">
                          Visualize which retinal regions influenced the AI's diagnostic decision
                        </p>
                      </div>

                      <div className="p-3 bg-muted rounded-lg">
                        <h4 className="font-medium mb-2">Key Findings:</h4>
                        <ul className="text-sm space-y-1">
                          {results.findings.map((finding: string, index: number) => (
                            <li key={index} className="flex items-start gap-2">
                              <CheckCircle className="h-4 w-4 text-green-600 mt-0.5 flex-shrink-0" />
                              {finding}
                            </li>
                          ))}
                        </ul>
                      </div>

                      <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
                        <h4 className="font-medium text-blue-900 mb-1">Recommendation:</h4>
                        <p className="text-sm text-blue-800">{results.recommendation}</p>
                      </div>
                    </div>

                    <div className="flex gap-2 mt-6">
                      <Button
                        variant="outline"
                        className="flex-1 bg-transparent"
                        onClick={downloadReport}
                        disabled={!results}
                      >
                        <Download className="h-4 w-4 mr-2" />
                        Download Report
                      </Button>
                      <Button variant="outline" className="flex-1 bg-transparent">
                        Share Results
                      </Button>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Medical Disclaimer */}
          <div className="mt-8 bg-yellow-50 border border-yellow-200 rounded-lg p-4">
            <div className="flex items-start gap-3">
              <AlertCircle className="h-5 w-5 text-yellow-600 mt-0.5 flex-shrink-0" />
              <div>
                <h4 className="font-semibold text-yellow-800 mb-1">Important Medical Disclaimer</h4>
                <p className="text-sm text-yellow-700">
                  This AI screening tool is designed to assist healthcare professionals and should not be used as a
                  substitute for professional medical diagnosis, treatment, or advice. Always consult with qualified
                  healthcare professionals for medical decisions. The results provided are for screening purposes only
                  and require clinical correlation and professional interpretation.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Grad-CAM Heatmap Modal */}
      {showHeatmapModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden">
            {/* Modal Header */}
            <div className="flex items-center justify-between p-6 border-b border-slate-200 bg-slate-50">
              <div>
                <h3 className="text-xl font-semibold text-slate-900">Grad-CAM Heatmap Analysis</h3>
                <p className="text-sm text-slate-600 mt-1">AI Decision Visualization</p>
              </div>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowHeatmapModal(false)}
                className="h-8 w-8 p-0 hover:bg-slate-200"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>

            {/* Modal Content */}
            <div className="p-6 overflow-y-auto">
              <div className="grid md:grid-cols-2 gap-6">
                {/* Original Image */}
                <div className="space-y-3">
                  <h4 className="font-medium text-slate-900">Original Retinal Image</h4>
                  <div className="relative bg-slate-100 rounded-lg overflow-hidden border-2 border-slate-200">
                    <img
                      src={uploadedImage || "/placeholder.svg"}
                      alt="Original retinal image"
                      className="w-full h-64 object-cover"
                    />
                  </div>
                </div>

                {/* Heatmap Overlay */}
                <div className="space-y-3">
                  <h4 className="font-medium text-slate-900">Grad-CAM Heatmap Overlay</h4>
                  <div className="relative bg-slate-100 rounded-lg overflow-hidden border-2 border-red-200">
                    {heatmap ? (
                      <img
                        src={`data:image/png;base64,${heatmap}`}
                        alt="Grad-CAM"
                        className="w-full h-64 object-cover"
                      />
                    ) : (
                      <img
                        src={uploadedImage || "/placeholder.svg"}
                        alt="Retinal image with heatmap"
                        className="w-full h-64 object-cover"
                      />
                    )}
                    <div className="absolute top-2 right-2">
                      <Badge className="bg-red-100 text-red-800 border-red-300">High Attention</Badge>
                    </div>
                  </div>
                </div>
              </div>

              {/* Explanation */}
              <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                <div className="flex items-start gap-3">
                  <Eye className="h-5 w-5 text-blue-600 mt-0.5 shrink-0" />
                  <div>
                    <h4 className="font-medium text-blue-900 mb-2">Heatmap Interpretation</h4>
                    <p className="text-sm text-blue-800 leading-relaxed">
                      This visualization highlights retinal regions influencing the AI's decision. Red and yellow areas
                      indicate regions of high attention where the model detected features relevant to diabetic
                      retinopathy classification. The intensity of colors corresponds to the importance of each region
                      in the final prediction.
                    </p>
                  </div>
                </div>
              </div>

              {/* Color Legend */}
              <div className="mt-4 p-4 bg-slate-50 border border-slate-200 rounded-lg">
                <h4 className="font-medium text-slate-900 mb-3">Color Legend</h4>
                <div className="flex items-center gap-6 text-sm">
                  <div className="flex items-center gap-2">
                    <div className="w-4 h-4 bg-red-500 rounded"></div>
                    <span className="text-slate-700">High Attention</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-4 h-4 bg-yellow-400 rounded"></div>
                    <span className="text-slate-700">Medium Attention</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-4 h-4 bg-slate-200 rounded"></div>
                    <span className="text-slate-700">Low Attention</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="flex justify-end gap-3 p-6 border-t border-slate-200 bg-slate-50">
              <Button
                variant="outline"
                onClick={() => setShowHeatmapModal(false)}
                className="bg-white hover:bg-slate-50"
              >
                Close
              </Button>
              <Button className="bg-blue-600 hover:bg-blue-700">
                <Download className="h-4 w-4 mr-2" />
                Save Heatmap
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
